mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    # maps /polls/
    path('', views.index, name='index'),
    # maps [eg]: /polls/3/
    path('<int:question_id>/', views.detail, name='detail'),
    # maps [eg]: /polls/3/results/
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Choice, Question


def index(request):
    return render(request, 'polls/index.html', {'questions': Question.objects.order_by('-pub_date')[:5]})


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choices = question.choice_set.order_by('votes', 'id')
    ctx = {'question': question, 'choices': choices}
    return render(request, 'polls/detail.html', ctx)


def results(request, question_id):
    return HttpResponse("You're looking at the results of question %s." % question_id)


def vote(request, question_id):
    return HttpResponse(f"You're voting on question {question_id}.")

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Poll Details</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in choices %}
        <li>{{ choice.choice_text }}</li>
        {% endfor %}
    </ul>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recent Polls</title>
</head>
<body>
    {% if questions %}
    <h3>Here are the latest polls:</h3>
    <table>
        <tr>
            <td>Poll</td>
            <td>Published</td>
        </tr>
        {% for question in questions %}
        <tr>
            <td><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></td>
            <td>{{ question.pub_date }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <h3>No polls to display.</h3>
    {% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Poll Results</title>
</head>
<body>

</body>
</html>

polls/templates/polls/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Voting</title>
</head>
<body>

</body>
</html>